### ISSUE TITLE
Nativescript 7 + angular 11 ( Module not found nativescript-emoji-picker-angular.js)

### ISSUE THREAD

**Issue by dudipsh** [SchoolSquirrel/nativescript-plugins#50]
Hi, 
@JonathanTreffler, @hrueger 

i get this error, 
angular.js
Module not found: Error: Can't resolve '@schoolsquirrel/emoji-picker' in '/Users/dudipartush/Documents/dev/TimeTalk/theGoodPlace/node_modules/@schoolsquirrel/emoji-picker/__ivy_ngcc__/angular/fesm2015'
 @ ../node_modules/@schoolsquirrel/emoji-picker/__ivy_ngcc__/angular/fesm2015/nativescript-emoji-picker-angular.js 3:0-71 14:37-48 15:36-46
 @ ./app/app.module.ts
 @ ./main.ts
`

Steps
1:  `ns plugin add @schoolsquirrel/emoji-picker`
2:  import EmojiPickerModule in appModule

```typescript

import {InjectionToken, NgModule, NO_ERRORS_SCHEMA} from "@angular/core";
import {
    NativeScriptCommonModule,
    NativeScriptFormsModule,
    NativeScriptHttpClientModule,
    NativeScriptModule
} from "@nativescript/angular";

import {AppRoutingModule} from "./app-routing.module";
import {AppComponent} from "./app.component";
import {ItemsComponent} from "./item/items.component";
import {ItemDetailComponent} from "./item/item-detail.component";
;
import {HTTP_INTERCEPTORS, HttpClient, HttpClientModule, HttpHeaders} from "@angular/common/http";
import {onError} from '@apollo/client/link/error';

import {InterceptorService} from "./factory/interceptor";
import {TranslateLoader, TranslateModule, TranslateService} from "@ngx-translate/core";
import {TranslateHttpLoader} from "@ngx-translate/http-loader";

import {CommonModule} from "@angular/common";
import {LetterAvatarModule} from "@schoolsquirrel/letter-avatar/angular";

import { EmojiPickerModule  } from "@schoolsquirrel/emoji-picker/angular";



@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        NativeScriptModule,
        NativeScriptHttpClientModule,
        AppRoutingModule,
        NativeScriptCommonModule,
        NativeScriptFormsModule,
        CommonModule,
        EmojiPickerModule,
        // EmojiModule,
        LoginModule,
    ],
    declarations: [
        AppComponent,
        ItemsComponent,
        ItemDetailComponent,

    ],
    providers: [
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class AppModule {
    constructor(
        private translate: TranslateService,
    ) {
        this.translate.setDefaultLang('en');
        translate.use('en');
    }

}

`

**Comment by hrueger** [comment]
Hi @dudipsh,
Thanks for the bug report. I'll look into that in a few days.

**Comment by hrueger** [comment]
I'm working on it.

**Comment by dudipsh** [comment]
@hrueger 
Hi,
I try to run 
`ns clean`
`ns plugin add @schoolsquirrel/emoji-picker`
`ns debug android --no-hmr`

`ERROR in ../node_modules/@schoolsquirrel/emoji-picker/__ivy_ngcc__/angular/fesm2015/schoolsquirrel-emoji-picker-angular.js
Module not found: Error: Can't resolve '@schoolsquirrel/emoji-picker' in '/Users/dudipartush/Documents/dev/TimeTalk/theGoodPlace/node_modules/@schoolsquirrel/emoji-picker/__ivy_ngcc__/angular/fesm2015'
 @ ../node_modules/@schoolsquirrel/emoji-picker/__ivy_ngcc__/angular/fesm2015/schoolsquirrel-emoji-picker-angular.js 3:0-71 14:37-48 15:36-46
 @ ./app/pages/channels/channels.module.tns.ts
 @ ./app/app.module.ts
 @ ./main.ts
`

**Comment by hrueger** [comment]
Hm, I can reproduce the error, however, I don't have any idea what the problem could be. I'll keep investigating

**Comment by hrueger** [comment]
Does `@schoolsquirrel/letter-avatar` work?

**Comment by dudipsh** [comment]
@hrueger 
Thanks for the help,
I'm working on something else right now, later or tomorrow I'll try to check it out again.
Then keep you posted

>> Does @schoolsquirrel/letter-avatar work?
>
  YES ! :)

**Comment by dudipsh** [comment]
@hrueger 
Hi, do you have working project in ns7 + ng 11?
its brake when i adding EmojiPickerModule to imports section

ERROR in ../node_modules/@schoolsquirrel/emoji-picker/__ivy_ngcc__/angular/fesm2015/schoolsquirrel-emoji-picker-angular.js

do i need to change my tsconfig.json?

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,

    "forceConsistentCasingInFileNames": true,
    "noEmitHelpers": true,
    "noEmitOnError": true,
    "skipLibCheck": true,
    "lib": [
      "es2018", "es2017", "dom", "es6"

    ],
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "app/*"
      ]
    }
  },
  "include": [
    "reference.d.ts",
    "src/**/*.ios.ts", "src/**/*.android.ts"
  ],
  "files": [
    "./references.d.ts",
    "./src/main.ts"
  ],
  "exclude": [
    "node_modules",
    "platforms",
    "**/*.aot",
    "e2e"

  ]

}

`

**Comment by hrueger** [comment]
@dudipsh 
No, sorry. I created a new test app but I get stuck with the same error you describe above. The weird thing is that letter-avatar is working fine, however, I cannot find differences between the two plugins which could cause the problem...

**Comment by dudipsh** [comment]
@hrueger 
any luck?

**Comment by hrueger** [comment]
No, unfortunately not. This is very strange

**Comment by hrueger** [comment]
@dudipsh Why did you close this? Did you get it working?

**Comment by dudipsh** [comment]
@hrueger 
yes its works! 
I am not sure if this is the only change to make it works

i added nativescript.config.ts in my root folder
```text
import { NativeScriptConfig } from '@nativescript/core';

export default {
  id: 'org.nativescript.goodplace',
  appPath: 'src',
  appResourcesPath: 'App_Resources',
  android: {
    v8Flags: '--expose_gc',
    markingMode: 'none'
  }
} as NativeScriptConfig;


```

**Comment by hrueger** [comment]
Great, thanks for the info!
